[FEAT]: latest changes

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -11,22 +11,30 @@ ARG USER_GID=$USER_UID
 # Avoid warnings by switching to noninteractive
 ENV DEBIAN_FRONTEND=noninteractive
 
+# For wifi configuration and settings
+ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
+
 WORKDIR /workspace/livox/
 
+# -----------------------------------------------------------------------------
+# Define user
 RUN groupadd --gid $USER_GID $USERNAME \
     && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
-    && apt-get update \
-    && apt-get install -y sudo \
+    # ------------------------------
+    # [Optional] Add sudo support for non-root user
+    && apt-get update && apt-get install -y sudo \
     && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
     && chmod 0440 /etc/sudoers.d/$USERNAME \
     # ------------------------------
+    # Clean up
+    && apt-get autoremove && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/* \
+    # ------------------------------
+    # WebCam Permission
+    && usermod -a -G video $USERNAME \
+    # ------------------------------
     # Lidar Permission
     && adduser ${USERNAME} dialout
-# Switch from root to user
-USER $USERNAME
-
-# Add user to video group to allow access to webcam
-RUN sudo usermod --append --groups video $USERNAME
 
 # Install 
 RUN sudo apt update && sudo apt upgrade -y \
@@ -35,10 +43,19 @@ RUN sudo apt update && sudo apt upgrade -y \
     git \
     libeigen3-dev \
     libceres-dev \
-    && rm -rf /home/ada/.cache/pip \
+    && rm -rf /home/ada/.cache/pip
 
 # Rosdep update
-RUN rosdep update
+RUN rosdep update \
+    && sudo rm /etc/machine-id \
+    && sudo systemd-machine-id-setup
+
 
 # Source the ROS setup file
-RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc
+RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/${USERNAME}/.bashrc \
+    && echo "source /workspace/ros/devel/setup.bash || true" >> /home/${USERNAME}/.bashrc
+
+# -----------------------------------------------------------------------------
+# Switch back to dialog for any ad-hoc use of apt-get
+ENV DEBIAN_FRONTEND=
+CMD ["/bin/bash"]
